Refactor/survey
Lambda-School-Labs/Labs26-Apollo-BE-TeamB pull request #38
Opened 2020-09-29 19:41 UTC by Caleb-Barger

## Before making the Pull Request:

this pr adds a "responded" field to requests that ask for a survey or a list of all surveys.
It also comes with a splash screen :D

- [x] Is there a description to this pull request that points to a specific user story, feature, or bugfix?
- [x] Are there comments where the code may be unclear?
- [x] Is all dead code, commented out code, etc. removed?
- [ ] Are there tests written for these changes?
- [ ] Does the ReadMe need to be updated?

## Before being merged by the TPL:

- [ ] Has the pull request been reviewed by at least two team members? 
- [ ] Did they leave any comments or suggestions? 
- [ ] Were those suggestions acted on?
- [ ] Are all tests passing?
- [ ] Has the documentation been updated?

2020-09-29 20:27 UTC, mcelroyian requested changes
Looks good 👍 Update Readme.

2020-09-29 23:01 UTC, jslohner submitted a review, later dismissed
Nice work 👍

2020-09-30 17:19 UTC, mcelroyian approved these changes
👍

2020-09-30 17:21 UTC, jiayi-ren approved these changes

2020-09-30 17:44 UTC, merged