fix compiling errors
Lambda-School-Labs/Labs26-Apollo-BE-TeamB pull request #6
Opened 2020-09-14 23:58 UTC by jiayi-ren

1. bugfix: fix topic controller compile errors

## Before making the Pull Request:

- [x] Is there a description to this pull request that points to a specific user story, feature, or bugfix?
- [ ] Are there comments where the code may be unclear?
- [ ] Is all dead code, commented out code, etc. removed?
- [ ] Are there tests written for these changes?
- [ ] Does the ReadMe need to be updated?

## Before being merged by the TPL:

- [ ] Has the pull request been reviewed by at least two team members? 
- [ ] Did they leave any comments or suggestions? 
- [ ] Were those suggestions acted on?
- [ ] Are all tests passing?
- [ ] Has the documentation been updated?

2020-09-14 23:59 UTC, mcelroyian submitted a review, later dismissed
Thanks, topics controller was bugged

2020-09-15 06:33 UTC, jjgorton requested changes

2020-09-15 06:33 UTC, jjgorton commented on src/main/java/com/lambdaschool/apollo/controllers/TopicController.java
> +//    @ApiOperation(value = "returns all Topics",
Can we remove this commented out code?

2020-09-15 15:55 UTC, mcelroyian approved these changes
no dead code

2020-09-15 15:57 UTC, jjgorton approved these changes

2020-09-15 15:57 UTC, merged